var images = { 
    
                    "ruse48" : ["images/bg/21054921_1585826328115708_1936933700740186281_o.jpg",
                            "images/bg/21055118_1585829398115401_7443525437990799614_o.jpg",
                            "images/bg/21056198_1585829788115362_8384074489932678166_o.jpg",
                            "images/bg/atelier-musique-concrete.jpg",
                            "images/bg/bibliotheque2.jpg",
                            "images/bg/bibliotheque.jpg",
                            "images/bg/chai faire chai dire.jpg",
                            "images/bg/lumieres.jpg",
                            "images/bg/photo Emetteur FM simple.jpg",
                            "images/bg/piezzo-2.jpg",
                            "images/bg/us17.png",
                            "images/bg/us-18-2.jpg",
                            "images/bg/us-18.jpg"
                            ],
    "nuit" : [ "images/bg/mix-chant.jpg", "images/bg/k7s.jpg", "images/bg/mixer.jpg",
  "images/bg/DSC03980.jpg",
  "images/bg/DSC04223.jpg",
  "images/bg/DSC04538.jpg",
  "images/bg/DSC07198.jpg",
  "images/bg/DSC07207.jpg",
  "images/bg/DSC07227.jpg",
  "images/bg/SL382140.jpg"
],
			   "journee" : [ "images/bg/rosace.jpg", "images/bg/walkman-herbe.jpg", 
							 "images/bg/radio-plantes.jpg", "images/bg/russian-radio.jpg",
							 "images/bg/vignettes.jpg", "images/bg/friche-russe.jpg",
							 "images/bg/radio-usine.jpg", "images/bg/chaine-journaux.jpg",
							 "images/bg/accordeon-allemand.jpg", "images/bg/concert-bobo.jpg",
							 "images/bg/incendie.jpg",
               "images/bg/Brest bateau.jpg",
               "images/bg/DSC04547.jpg",
               "images/bg/DSC07154.jpg",
               "images/bg/DSC07162.jpg",
               "images/bg/DSC07180.jpg",
               "images/bg/IMG_0108.jpg",
               "images/bg/IMG_0110.jpg",
               "images/bg/IMG_0133.jpg",
               "images/bg/IMG_0325.jpg",
               "images/bg/IMG_2245.jpg",
               "images/bg/DSCF0093.JPG",
               "images/bg/DSCF0237.JPG",
               "images/bg/DSCF0249.JPG"
   						],
			   "soiree" : [ "images/bg/dj-mix.jpg", "images/bg/goa.jpg", 
							"images/bg/frequence.jpg", "images/bg/blaukauss.jpg", 
							"images/bg/djembe.jpg", "images/bg/tuning.jpg",
							"images/bg/velo.jpg", /*"images/bg/live.jpg",*/ "images/bg/lights.jpg",
              "images/bg/263203_vignette_Brel-Ferre-Brassens.jpg",
              "images/bg/DSC06718.jpg",
              "images/bg/DSC06778.jpg",
              "images/bg/IMG_2277.jpg",
              "images/bg/IMG_2280.jpg",
              "images/bg/Place de Jaude.jpg",
              "images/bg/DSCF0126.JPG"
                    ],

			   "defaut" : [ "images/bg/radio-urbex.jpg" ] };
